SUBROUTINE RANU3(IX,A,N,ISW,IVW,ICON)
  IMPLICIT REAL*8(A-H,O-Z)
  DIMENSION A(N),IVW(128)
  REAL*8 AM,AA,AC,X,AIVW
  
  AM=2D0**31
  
  AA=32771D0
  AC=1234567891D0
  X=DFLOAT(IX)
  
  DO J=1,128
     X=DMOD(AA*X+AC,AM)
     IVW(J)=INT(X)
  ENDDO
  
  DO K=1,N
     X=DMOD(AA*X+AC,AM)
     KX=INT(X)
     KK=MOD(KX,128)+1
     AIVW=IVW(KK)
     A(K)=AIVW/AM
     IVW(KK)=KX
  ENDDO
  IX=X
  RETURN
END SUBROUTINE RANU3
